proto_library(
    name = "rpc_proto",
    srcs = [
        "rpc.proto"
    ],
)

proto_library(
    name = "node_proto",
    srcs = "node.proto"
)

proto_library(
    name = "session_proto",
    srcs = "session.proto"
)
