cc_library(
    name = "common",
    srcs = [
        "watch_event.cc",
        "status.cc",
        "node.cc",
        "address.cc",
        "event_log.cc"
    ],
    deps = [
        "//pyxis/proto:rpc_proto",
        "//pyxis/proto:node_proto",
        "//pyxis/proto:session_proto",
        "//toft/base/string:string",
        "//thirdparty/muduo:muduo_net"
    ]
 )
